package com.jk.designuijeetpackcompose.ui.theme


import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0A5BBF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A41)
val md_theme_light_secondary = Color(0xFF235FA6)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD5E3FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001B3B)
val md_theme_light_tertiary = Color(0xFF0061A3)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001D36)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF001849)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF001849)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474F)
val md_theme_light_outline = Color(0xFF75777F)
val md_theme_light_inverseOnSurface = Color(0xFFEEF0FF)
val md_theme_light_inverseSurface = Color(0xFF002B75)
val md_theme_light_inversePrimary = Color(0xFFADC6FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0A5BBF)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFADC6FF)
val md_theme_dark_onPrimary = Color(0xFF002E69)
val md_theme_dark_primaryContainer = Color(0xFF004494)
val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_secondary = Color(0xFFA7C8FF)
val md_theme_dark_onSecondary = Color(0xFF003060)
val md_theme_dark_secondaryContainer = Color(0xFF004788)
val md_theme_dark_onSecondaryContainer = Color(0xFFD5E3FF)
val md_theme_dark_tertiary = Color(0xFF9ECAFF)
val md_theme_dark_onTertiary = Color(0xFF003258)
val md_theme_dark_tertiaryContainer = Color(0xFF00497D)
val md_theme_dark_onTertiaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001849)
val md_theme_dark_onBackground = Color(0xFFDBE1FF)
val md_theme_dark_surface = Color(0xFF001849)
val md_theme_dark_onSurface = Color(0xFFDBE1FF)
val md_theme_dark_surfaceVariant = Color(0xFF44474F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF001849)
val md_theme_dark_inverseSurface = Color(0xFFDBE1FF)
val md_theme_dark_inversePrimary = Color(0xFF0A5BBF)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFADC6FF)
val md_theme_dark_outlineVariant = Color(0xFF44474F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF407CE2)
val CustomwhiteColor = Color(0xFFE8E8E8)
val light_CustomwhiteColor = Color(0xFF006874)
val light_onCustomwhiteColor = Color(0xFFFFFFFF)
val light_CustomwhiteColorContainer = Color(0xFF97F0FF)
val light_onCustomwhiteColorContainer = Color(0xFF001F24)
val dark_CustomwhiteColor = Color(0xFF4FD8EB)
val dark_onCustomwhiteColor = Color(0xFF00363D)
val dark_CustomwhiteColorContainer = Color(0xFF004F58)
val dark_onCustomwhiteColorContainer = Color(0xFF97F0FF)
